"""delete ledger

Revision ID: 0a940be75210
Revises: 76031f51b1fc
Create Date: 2026-08-03 19:28:59.113141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a940be75210'
down_revision: Union[str, Sequence[str], None] = '76031f51b1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transaction_ledger_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_table('ledger')
    op.drop_index(op.f('ix_transaction_ledger_id'), table_name='transaction')
    op.drop_column('transaction', 'ledger_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('ledger_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('transaction_ledger_id_fkey'), 'transaction', 'ledger', ['ledger_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_transaction_ledger_id'), 'transaction', ['ledger_id'], unique=False)
    op.create_table('ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ledger_pkey')),
    sa.UniqueConstraint('name', name=op.f('ledger_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
