"""budget_class

Revision ID: 108d79df0a23
Revises: 3d72fb0abc41
Create Date: 2026-09-02 21:17:47.906296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108d79df0a23'
down_revision: Union[str, Sequence[str], None] = '3d72fb0abc41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('budget_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'budget_class')
    # ### end Alembic commands ###
