"""gc_rules_payee_narration

Revision ID: 10eeeec539cc
Revises: 4f9279cec83b
Create Date: 2026-07-29 00:57:54.930398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10eeeec539cc'
down_revision: Union[str, Sequence[str], None] = '4f9279cec83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gocardless_import_rule', sa.Column('payee', sa.String(), nullable=True))
    op.add_column('gocardless_import_rule', sa.Column('narration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gocardless_import_rule', 'narration')
    op.drop_column('gocardless_import_rule', 'payee')
    # ### end Alembic commands ###
