"""budget_class_remove

Revision ID: 10f7db0cad4d
Revises: 108d79df0a23
Create Date: 2026-09-05 22:02:46.697663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f7db0cad4d'
down_revision: Union[str, Sequence[str], None] = '108d79df0a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'budget_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('budget_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
