"""monzo-merchant

Revision ID: 15206d920f8a
Revises: 0a940be75210
Create Date: 2026-08-14 18:33:14.416952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15206d920f8a'
down_revision: Union[str, Sequence[str], None] = '0a940be75210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monzo_import_rule', sa.Column('merchant_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monzo_import_rule', 'merchant_name')
    # ### end Alembic commands ###
