"""monzo_importer_rules

Revision ID: 1bb88b954b2c
Revises: 3fc65d6e6137
Create Date: 2026-07-26 20:22:48.949390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bb88b954b2c'
down_revision: Union[str, Sequence[str], None] = '3fc65d6e6137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monzo_import_rule',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('import_integration_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('payee', sa.String(), nullable=True),
    sa.Column('narration', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('pot_id', sa.String(), nullable=True),
    sa.Column('merchant_group_id', sa.String(), nullable=True),
    sa.Column('counterparty_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['import_integration_id'], ['monzo_importer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monzo_import_rule')
    # ### end Alembic commands ###
