"""add_type

Revision ID: 241cf7c36300
Revises: 58922d4a2ad5
Create Date: 2026-08-26 21:10:55.351986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241cf7c36300'
down_revision: Union[str, Sequence[str], None] = '58922d4a2ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('type', sa.String(), nullable=False))
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_column('notification', 'type')
    # ### end Alembic commands ###
