"""groups_mandatory

Revision ID: 3d72fb0abc41
Revises: 64d818c48d9d
Create Date: 2026-08-30 20:11:51.545236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d72fb0abc41'
down_revision: Union[str, Sequence[str], None] = '64d818c48d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
