"""gc_rules

Revision ID: 4f9279cec83b
Revises: 9da6cb08c70d
Create Date: 2026-07-29 00:52:12.655363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f9279cec83b'
down_revision: Union[str, Sequence[str], None] = '9da6cb08c70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gocardless_import_rule',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('import_integration_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('credit_only', sa.Boolean(), nullable=False),
    sa.Column('debit_only', sa.Boolean(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('account_name_matches', sa.String(), nullable=True),
    sa.Column('reference_name_matches', sa.String(), nullable=True),
    sa.Column('amount_equals', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['import_integration_id'], ['go_cardless_importer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gocardless_import_rule')
    # ### end Alembic commands ###
