"""new_metadata_data

Revision ID: 5374c2d054fe
Revises: 71ba8ca86481
Create Date: 2026-08-28 18:47:53.930965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5374c2d054fe'
down_revision: Union[str, Sequence[str], None] = '71ba8ca86481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE transaction
        SET ledger_metadata = metadata 
        WHERE metadata IS NOT NULL AND (ledger_metadata IS NULL OR ledger_metadata = '{}'::jsonb);
        """
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
