"""unique entry

Revision ID: 5f8004f024eb
Revises: 62c707d2c986
Create Date: 2026-07-06 21:18:34.018507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8004f024eb'
down_revision: Union[str, Sequence[str], None] = '62c707d2c986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_entries_tx_account', 'entry', ['transaction_id', 'account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_entries_tx_account', 'entry', type_='unique')
    # ### end Alembic commands ###
