"""ledger

Revision ID: 62c707d2c986
Revises: b531f20de2a1
Create Date: 2026-07-05 15:58:32.978222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62c707d2c986'
down_revision: Union[str, Sequence[str], None] = 'b531f20de2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    account_type_enum = postgresql.ENUM(
        'ASSET', 'EXPENSE', 'LIABILITY', 'EQUITY', 'INCOME',
        name='accounttype'
    )
    account_type_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('account', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
                postgresql_using="id::uuid")

    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_column('account', 'type')

    op.create_table('ledger',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ledger_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_datetime', sa.DateTime(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('payee', sa.String(), nullable=True),
    sa.Column('narration', sa.String(), nullable=True),
    sa.Column('external_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledger.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_key'), 'transaction', ['key'], unique=True)
    op.create_index(op.f('ix_transaction_ledger_id'), 'transaction', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_datetime'), 'transaction', ['transaction_datetime'], unique=False)
    op.create_table('entry',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('local_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('local_currency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_account_id'), 'entry', ['account_id'], unique=False)
    op.create_index(op.f('ix_entry_transaction_id'), 'entry', ['transaction_id'], unique=False)

    op.add_column('account', sa.Column('account_type', sa.Enum('ASSET', 'EXPENSE', 'LIABILITY', 'EQUITY', 'INCOME', name='accounttype'), nullable=False))
    op.add_column('account', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.alter_column('account', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('account', 'tags')
    op.drop_column('account', 'account_type')
    op.drop_index(op.f('ix_entry_transaction_id'), table_name='entry')
    op.drop_index(op.f('ix_entry_account_id'), table_name='entry')
    op.drop_table('entry')
    op.drop_index(op.f('ix_transaction_transaction_datetime'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_ledger_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_key'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('ledger')
    # ### end Alembic commands ###
