"""groups_data

Revision ID: 64d818c48d9d
Revises: fc50e3794d1b
Create Date: 2026-08-30 20:07:03.836258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d818c48d9d'
down_revision: Union[str, Sequence[str], None] = 'fc50e3794d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE transaction
        SET group_id = key 
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
