"""unqiue-account

Revision ID: 95691255c162
Revises: 33753725db89
Create Date: 2026-07-19 19:17:19.357033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95691255c162'
down_revision: Union[str, Sequence[str], None] = '33753725db89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('account_name_key'), 'account', type_='unique')
    op.create_unique_constraint('uq_name_and_type', 'account', ['name', 'account_type'])
    op.drop_index(op.f('idx_transactions_search_trgm'), table_name='transaction', postgresql_ops={'immutable_transaction_search_vector(payee::text, narration::text, tags::text[])': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_transactions_search_trgm'), 'transaction', [sa.literal_column('immutable_transaction_search_vector(payee::text, narration::text, tags::text[])')], unique=False, postgresql_ops={'immutable_transaction_search_vector(payee::text, narration::text, tags::text[])': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint('uq_name_and_type', 'account', type_='unique')
    op.create_unique_constraint(op.f('account_name_key'), 'account', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
