"""monzo_importer_adjust

Revision ID: 9da6cb08c70d
Revises: 1bb88b954b2c
Create Date: 2026-07-26 21:41:56.026270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9da6cb08c70d'
down_revision: Union[str, Sequence[str], None] = '1bb88b954b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monzo_import_rule', sa.Column('name', sa.String(), nullable=False))
    op.add_column('monzo_import_rule', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('monzo_import_rule', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('monzo_import_rule', sa.Column('transaction_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monzo_import_rule', 'transaction_id')
    op.drop_column('monzo_import_rule', 'metadata')
    op.drop_column('monzo_import_rule', 'priority')
    op.drop_column('monzo_import_rule', 'name')
    # ### end Alembic commands ###
