"""import_integration-config

Revision ID: d2a9186487be
Revises: 2c1e6b2f4a9d
Create Date: 2026-07-31 17:44:12.458853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a9186487be'
down_revision: Union[str, Sequence[str], None] = '2c1e6b2f4a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('go_cardless_importer', sa.Column('cash_account_id', sa.Uuid(), nullable=True))
    op.add_column('go_cardless_importer', sa.Column('default_income_account_id', sa.Uuid(), nullable=True))
    op.add_column('go_cardless_importer', sa.Column('default_expense_account_id', sa.Uuid(), nullable=True))
    op.add_column('monzo_importer', sa.Column('cash_account_id', sa.Uuid(), nullable=True))
    op.add_column('monzo_importer', sa.Column('default_income_account_id', sa.Uuid(), nullable=True))
    op.add_column('monzo_importer', sa.Column('default_expense_account_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monzo_importer', 'default_expense_account_id')
    op.drop_column('monzo_importer', 'default_income_account_id')
    op.drop_column('monzo_importer', 'cash_account_id')
    op.drop_column('go_cardless_importer', 'default_expense_account_id')
    op.drop_column('go_cardless_importer', 'default_income_account_id')
    op.drop_column('go_cardless_importer', 'cash_account_id')
    # ### end Alembic commands ###
