"""groups

Revision ID: f2a0cac09ba8
Revises: 5f3a233c2225
Create Date: 2026-08-30 20:04:11.816365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a0cac09ba8'
down_revision: Union[str, Sequence[str], None] = '5f3a233c2225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('group_id', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('succeeded_by_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'succeeded_by_group')
    op.drop_column('transaction', 'group_id')
    # ### end Alembic commands ###
