"""groups2

Revision ID: fc50e3794d1b
Revises: f2a0cac09ba8
Create Date: 2026-08-30 20:06:35.288596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc50e3794d1b'
down_revision: Union[str, Sequence[str], None] = 'f2a0cac09ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('superseded_by_group', sa.String(), nullable=True))
    op.drop_column('transaction', 'succeeded_by_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('succeeded_by_group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'superseded_by_group')
    # ### end Alembic commands ###
